name: Deploy Next.js to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18



      - name: Navigate to Frontend Directory and install packages
        run: |
            (
              cd frontend/
              npm install
              npm run build
            )
      - name : Build nextjs application
        run : |
            (
              cd frontend/
              npm run build
            )
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Deploy to S3
        run: |
          (
          cd frontend/
          aws s3 sync ./out/ s3://carykuang.com
          )

