name: Deploy Next.js to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Navigate to Frontend Directory and install packages
        run: |
            (
              cd frontend/
              npm install
              npm run build
            )
      - name : Build nextjs application
        run : |
            (
              cd frontend/
              npm run build
            )
      - name: Deploy to S3
        run: |
          aws s3 sync ./out/ s3://carykuang.com
    
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
