name: Test Lambda Function

on:
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest 
    env:  # Set environment variables using GitHub Secrets
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2 

      - name: Set up Python
        uses: actions/setup-python@v2  
        with:
          python-version: 3.8  
      - name: Install Dependencies
        run: pip install -r requirements.txt  
  
      - name: Run Tests
        run: python backend/tests/test_lambda.py  
      
 
